// <auto-generated />
using System;
using ComicTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicTracker.Data.Migrations
{
    [DbContext(typeof(ComicTrackerDbContext))]
    [Migration("20210617201114_TemplateModelsAdded")]
    partial class TemplateModelsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComicTracker.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ComicTracker.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ComicTracker.Data.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Arc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SeriesId" }, "IX_Arcs_SeriesId");

                    b.ToTable("Arcs");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcArtist", b =>
                {
                    b.Property<int>("ArcsId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.HasKey("ArcsId", "ArtistsId");

                    b.HasIndex(new[] { "ArtistsId" }, "IX_ArcArtist_ArtistsId");

                    b.ToTable("ArcArtist");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcGenre", b =>
                {
                    b.Property<int>("ArcsId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("ArcsId", "GenresId");

                    b.HasIndex(new[] { "GenresId" }, "IX_ArcGenre_GenresId");

                    b.ToTable("ArcGenre");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcPublisher", b =>
                {
                    b.Property<int>("ArcsId")
                        .HasColumnType("int");

                    b.Property<int>("PublishersId")
                        .HasColumnType("int");

                    b.HasKey("ArcsId", "PublishersId");

                    b.HasIndex(new[] { "PublishersId" }, "IX_ArcPublisher_PublishersId");

                    b.ToTable("ArcPublisher");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcVolume", b =>
                {
                    b.Property<int>("ArcId")
                        .HasColumnType("int");

                    b.Property<int>("VolumeId")
                        .HasColumnType("int");

                    b.HasKey("ArcId", "VolumeId");

                    b.HasIndex(new[] { "VolumeId" }, "IX_ArcVolume_VolumeId");

                    b.ToTable("ArcVolume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcWriter", b =>
                {
                    b.Property<int>("ArcsId")
                        .HasColumnType("int");

                    b.Property<int>("WritersId")
                        .HasColumnType("int");

                    b.HasKey("ArcsId", "WritersId");

                    b.HasIndex(new[] { "WritersId" }, "IX_ArcWriter_WritersId");

                    b.ToTable("ArcWriter");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NationalityId" }, "IX_Artists_NationalityId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArtistIssue", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.Property<int>("IssuesId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsId", "IssuesId");

                    b.HasIndex(new[] { "IssuesId" }, "IX_ArtistIssue_IssuesId");

                    b.ToTable("ArtistIssue");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArtistSeries", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsId", "SeriesId");

                    b.HasIndex(new[] { "SeriesId" }, "IX_ArtistSeries_SeriesId");

                    b.ToTable("ArtistSeries");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArtistVolume", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.Property<int>("VolumesId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsId", "VolumesId");

                    b.HasIndex(new[] { "VolumesId" }, "IX_ArtistVolume_VolumesId");

                    b.ToTable("ArtistVolume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstAppearance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersArc", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ArcId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMainCharacter")
                        .HasColumnType("bit");

                    b.HasKey("CharacterId", "ArcId");

                    b.HasIndex(new[] { "ArcId" }, "IX_CharactersArcs_ArcId");

                    b.ToTable("CharactersArcs");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersIssue", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMainCharacter")
                        .HasColumnType("bit");

                    b.HasKey("CharacterId", "IssueId");

                    b.HasIndex(new[] { "IssueId" }, "IX_CharactersIssues_IssueId");

                    b.ToTable("CharactersIssues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersSeries", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMainCharacter")
                        .HasColumnType("bit");

                    b.HasKey("CharacterId", "SeriesId");

                    b.HasIndex(new[] { "SeriesId" }, "IX_CharactersSeries_SeriesId");

                    b.ToTable("CharactersSeries");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersVolume", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("VolumeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMainCharacter")
                        .HasColumnType("bit");

                    b.HasKey("CharacterId", "VolumeId");

                    b.HasIndex(new[] { "VolumeId" }, "IX_CharactersVolumes_VolumeId");

                    b.ToTable("CharactersVolumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.GenreIssue", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("IssuesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "IssuesId");

                    b.HasIndex(new[] { "IssuesId" }, "IX_GenreIssue_IssuesId");

                    b.ToTable("GenreIssue");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.GenreSeries", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "SeriesId");

                    b.HasIndex(new[] { "SeriesId" }, "IX_GenreSeries_SeriesId");

                    b.ToTable("GenreSeries");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.GenreVolume", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("VolumesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "VolumesId");

                    b.HasIndex(new[] { "VolumesId" }, "IX_GenreVolume_VolumesId");

                    b.ToTable("GenreVolume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArcId")
                        .HasColumnType("int");

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("VolumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ArcId" }, "IX_Issues_ArcId");

                    b.HasIndex(new[] { "SeriesId" }, "IX_Issues_SeriesId");

                    b.HasIndex(new[] { "VolumeId" }, "IX_Issues_VolumeId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.IssueWriter", b =>
                {
                    b.Property<int>("IssuesId")
                        .HasColumnType("int");

                    b.Property<int>("WritersId")
                        .HasColumnType("int");

                    b.HasKey("IssuesId", "WritersId");

                    b.HasIndex(new[] { "WritersId" }, "IX_IssueWriter_WritersId");

                    b.ToTable("IssueWriter");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NationalityId" }, "IX_Publishers_NationalityId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.PublisherSeries", b =>
                {
                    b.Property<int>("PublishersId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("PublishersId", "SeriesId");

                    b.HasIndex(new[] { "SeriesId" }, "IX_PublisherSeries_SeriesId");

                    b.ToTable("PublisherSeries");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.PublishersIssue", b =>
                {
                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PublisherId", "IssueId");

                    b.HasIndex(new[] { "IssueId" }, "IX_PublishersIssues_IssueId");

                    b.ToTable("PublishersIssues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.PublishersVolume", b =>
                {
                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("VolumeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PublisherId", "VolumeId");

                    b.HasIndex(new[] { "VolumeId" }, "IX_PublishersVolumes_VolumeId");

                    b.ToTable("PublishersVolumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.SeriesWriter", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int>("WritersId")
                        .HasColumnType("int");

                    b.HasKey("SeriesId", "WritersId");

                    b.HasIndex(new[] { "WritersId" }, "IX_SeriesWriter_WritersId");

                    b.ToTable("SeriesWriter");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Volume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SeriesId" }, "IX_Volumes_SeriesId");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.VolumeWriter", b =>
                {
                    b.Property<int>("VolumesId")
                        .HasColumnType("int");

                    b.Property<int>("WritersId")
                        .HasColumnType("int");

                    b.HasKey("VolumesId", "WritersId");

                    b.HasIndex(new[] { "WritersId" }, "IX_VolumeWriter_WritersId");

                    b.ToTable("VolumeWriter");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NationalityId" }, "IX_Writers_NationalityId");

                    b.ToTable("Writers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Arc", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("Arcs")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcArtist", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arcs")
                        .WithMany("ArcArtists")
                        .HasForeignKey("ArcsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Artist", "Artists")
                        .WithMany("ArcArtists")
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arcs");

                    b.Navigation("Artists");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcGenre", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arcs")
                        .WithMany("ArcGenres")
                        .HasForeignKey("ArcsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Genre", "Genres")
                        .WithMany("ArcGenres")
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arcs");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcPublisher", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arcs")
                        .WithMany("ArcPublishers")
                        .HasForeignKey("ArcsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Publisher", "Publishers")
                        .WithMany("ArcPublishers")
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arcs");

                    b.Navigation("Publishers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcVolume", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arc")
                        .WithMany("ArcVolumes")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Volume", "Volume")
                        .WithMany("ArcVolumes")
                        .HasForeignKey("VolumeId")
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArcWriter", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arcs")
                        .WithMany("ArcWriters")
                        .HasForeignKey("ArcsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Writer", "Writers")
                        .WithMany("ArcWriters")
                        .HasForeignKey("WritersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arcs");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Artist", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Nationality", "Nationality")
                        .WithMany("Artists")
                        .HasForeignKey("NationalityId");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArtistIssue", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Artist", "Artists")
                        .WithMany("ArtistIssues")
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Issue", "Issues")
                        .WithMany("ArtistIssues")
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artists");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArtistSeries", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Artist", "Artists")
                        .WithMany("ArtistSeries")
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("ArtistSeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artists");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.ArtistVolume", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Artist", "Artists")
                        .WithMany("ArtistVolumes")
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Volume", "Volumes")
                        .WithMany("ArtistVolumes")
                        .HasForeignKey("VolumesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artists");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersArc", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arc")
                        .WithMany("CharactersArcs")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Character", "Character")
                        .WithMany("CharactersArcs")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersIssue", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Character", "Character")
                        .WithMany("CharactersIssues")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Issue", "Issue")
                        .WithMany("CharactersIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersSeries", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Character", "Character")
                        .WithMany("CharactersSeries")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("CharactersSeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.CharactersVolume", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Character", "Character")
                        .WithMany("CharactersVolumes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Volume", "Volume")
                        .WithMany("CharactersVolumes")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.GenreIssue", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Genre", "Genres")
                        .WithMany("GenreIssues")
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Issue", "Issues")
                        .WithMany("GenreIssues")
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genres");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.GenreSeries", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Genre", "Genres")
                        .WithMany("GenreSeries")
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("GenreSeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genres");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.GenreVolume", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Genre", "Genres")
                        .WithMany("GenreVolumes")
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Volume", "Volumes")
                        .WithMany("GenreVolumes")
                        .HasForeignKey("VolumesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genres");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Issue", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Arc", "Arc")
                        .WithMany("Issues")
                        .HasForeignKey("ArcId");

                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("Issues")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Volume", "Volume")
                        .WithMany("Issues")
                        .HasForeignKey("VolumeId");

                    b.Navigation("Arc");

                    b.Navigation("Series");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.IssueWriter", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Issue", "Issues")
                        .WithMany("IssueWriters")
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Writer", "Writers")
                        .WithMany("IssueWriters")
                        .HasForeignKey("WritersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issues");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Publisher", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Nationality", "Nationality")
                        .WithMany("Publishers")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.PublisherSeries", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Publisher", "Publishers")
                        .WithMany("PublisherSeries")
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("PublisherSeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publishers");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.PublishersIssue", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Issue", "Issue")
                        .WithMany("PublishersIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Publisher", "Publisher")
                        .WithMany("PublishersIssues")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.PublishersVolume", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Publisher", "Publisher")
                        .WithMany("PublishersVolumes")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Volume", "Volume")
                        .WithMany("PublishersVolumes")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.SeriesWriter", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("SeriesWriters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Writer", "Writers")
                        .WithMany("SeriesWriters")
                        .HasForeignKey("WritersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Volume", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Series", "Series")
                        .WithMany("Volumes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.VolumeWriter", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Volume", "Volumes")
                        .WithMany("VolumeWriters")
                        .HasForeignKey("VolumesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Web.Models.Writer", "Writers")
                        .WithMany("VolumeWriters")
                        .HasForeignKey("WritersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Volumes");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Writer", b =>
                {
                    b.HasOne("ComicTracker.Web.Models.Nationality", "Nationality")
                        .WithMany("Writers")
                        .HasForeignKey("NationalityId");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ComicTracker.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ComicTracker.Data.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ComicTracker.Data.Models.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ComicTracker.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComicTracker.Data.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ComicTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ComicTracker.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Arc", b =>
                {
                    b.Navigation("ArcArtists");

                    b.Navigation("ArcGenres");

                    b.Navigation("ArcPublishers");

                    b.Navigation("ArcVolumes");

                    b.Navigation("ArcWriters");

                    b.Navigation("CharactersArcs");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Artist", b =>
                {
                    b.Navigation("ArcArtists");

                    b.Navigation("ArtistIssues");

                    b.Navigation("ArtistSeries");

                    b.Navigation("ArtistVolumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Character", b =>
                {
                    b.Navigation("CharactersArcs");

                    b.Navigation("CharactersIssues");

                    b.Navigation("CharactersSeries");

                    b.Navigation("CharactersVolumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Genre", b =>
                {
                    b.Navigation("ArcGenres");

                    b.Navigation("GenreIssues");

                    b.Navigation("GenreSeries");

                    b.Navigation("GenreVolumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Issue", b =>
                {
                    b.Navigation("ArtistIssues");

                    b.Navigation("CharactersIssues");

                    b.Navigation("GenreIssues");

                    b.Navigation("IssueWriters");

                    b.Navigation("PublishersIssues");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Nationality", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Publishers");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Publisher", b =>
                {
                    b.Navigation("ArcPublishers");

                    b.Navigation("PublisherSeries");

                    b.Navigation("PublishersIssues");

                    b.Navigation("PublishersVolumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Series", b =>
                {
                    b.Navigation("Arcs");

                    b.Navigation("ArtistSeries");

                    b.Navigation("CharactersSeries");

                    b.Navigation("GenreSeries");

                    b.Navigation("Issues");

                    b.Navigation("PublisherSeries");

                    b.Navigation("SeriesWriters");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Volume", b =>
                {
                    b.Navigation("ArcVolumes");

                    b.Navigation("ArtistVolumes");

                    b.Navigation("CharactersVolumes");

                    b.Navigation("GenreVolumes");

                    b.Navigation("Issues");

                    b.Navigation("PublishersVolumes");

                    b.Navigation("VolumeWriters");
                });

            modelBuilder.Entity("ComicTracker.Web.Models.Writer", b =>
                {
                    b.Navigation("ArcWriters");

                    b.Navigation("IssueWriters");

                    b.Navigation("SeriesWriters");

                    b.Navigation("VolumeWriters");
                });
#pragma warning restore 612, 618
        }
    }
}
